name: BASE

namespaces:
  - "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  - "http://www.w3.org/2000/01/rdf-schema#"

allowed_classes:
  - Statement
  - Property
  - Container
  - Datatype
  - Literal
  - Resource
  - Concept

# ======================
# MAPPER
# ======================
mapper:
  # ========== Classification, no behavior ==========

  rdfs:Literal:
    is: class
    target_class: Literal

  # All definitions belonging to reasoning are excluded
  # such as owl:bottomObjectPorperty owl:topObjectProperty, owl:bottomObjectProperty, owl:topDataProperty, owl:bottomDataProperty, owl:Thing, owl:Nothing


  # rdfs:Container, rdfs:ContainerMembershipProperty, rdfs:member
  # skos:memberList, skos:narrower [!!], skos:inScheme [!!!], skos:narrowerTransitive, skos:semanticRelation, skos:broaderTransitive, skos:mappingRelation

  rdfs:Datatype:
    is: class
    target_class: Datatype 

  rdf:Property:
    is: class
    target_class: Property
  
  # ========== Property ==========
  rdfs:domain:
    is: predicate
    target_classes: [Property]
    setters: [set_has_domain: Concept]
    
  rdfs:range:
    is: predicate
    target_classes: [Property]
    handler: handle_range
    setters: [set_has_range: Resource]
    
  rdfs:subPropertyOf:
    is: predicate
    target_classes: [Property]
    setters: [set_is_sub_property_of: Property]
  
  # ========== Concept ==========
  rdfs:subClassOf:
    is: predicate
    target_classes: [Concept]
    setters: [set_is_sub_concept_of: Concept]
  
  # ========== Statement/Annotation ==========
  
  rdfs:Class:
    is: class
    target_class: Concept
  

  
  # owl:Thing:
  #   is: class
  #   target_class: Individual
  
  # owl:Nothing:
  #   is: class
  #   target_class: Individual


  # ========== Resource ==========

  rdfs:Resource:
    is: class 
    target_class: Resource

  rdfs:label:
    is: predicate
    target_classes: [Resource]
    setters: [set_has_label: Literal]
    
  rdfs:comment:
    is: predicate
    target_classes: [Resource]
    setters: [set_has_comment: Literal]
  
  # ========== Resource Object Properties ==========
  rdfs:seeAlso:
    is: predicate
    target_classes: [Resource]
    setters: [set_see_also: Resource]

  rdfs:isDefinedBy:
    is: predicate
    target_classes: [Resource]
    setters: [set_is_defined_by: Resource]
  
  rdf:type:
    is: predicate
    target_classes: [Individual, Resource]
    setters: [set_has_type: Concept]

# ======================
# ENRICHER
# ======================
